# Generated by Django 4.2 on 2026-02-17 00:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_userprofile_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='course_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='classroom',
            name='schedule',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='units',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='performancemonitoring',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performancemonitoring',
            name='performance_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('exam', 'Exam'), ('assignment', 'Assignment'), ('project', 'Project'), ('others', 'Others')], default='others', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='performancemonitoring',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
