# Generated by Django 4.2 on 2026-02-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_userprofile_birthday_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
    ]
