# Generated by Django 4.2 on 2026-02-18 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_userprofile_birthday_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancemonitoring',
            options={'verbose_name': 'Academic Record', 'verbose_name_plural': 'Academic Records'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
    ]
