# Generated by Django 4.2 on 2026-02-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_alter_performancemonitoring_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
            ],
            options={
                'verbose_name': 'Academic Record (Exam)',
                'verbose_name_plural': 'Academic Records (Exams)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portal.performancemonitoring',),
        ),
        migrations.CreateModel(
            name='StudentScore',
            fields=[
            ],
            options={
                'verbose_name': 'Student Score (Quiz/Asst)',
                'verbose_name_plural': 'Student Scores (Quiz/Asst)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('portal.performancemonitoring',),
        ),
        migrations.AlterModelOptions(
            name='performancemonitoring',
            options={'verbose_name': 'All Performance Record', 'verbose_name_plural': 'All Performance Records'},
        ),
        migrations.AddField(
            model_name='performancemonitoring',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='performancemonitoring',
            name='performance_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('exam', 'Exam'), ('assignment', 'Assignment'), ('project', 'Project'), ('activity', 'Activity'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
