# Generated by Django 4.2 on 2026-02-21 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_tasksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='performance_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='portal.performancemonitoring'),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='submission_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='content',
            field=models.TextField(blank=True, help_text='Submit links, text, or a summary of your work.'),
        ),
    ]
