# Generated by Django 4.2 on 2026-02-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_tasksubmission_performance_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemonitoring',
            name='task_instructions',
            field=models.TextField(blank=True, help_text='Questions or instructions for the student.'),
        ),
        migrations.AlterField(
            model_name='performancemonitoring',
            name='remarks',
            field=models.TextField(blank=True, help_text="Teacher's feedback after grading."),
        ),
    ]
