# Generated by Django 4.2 on 2026-02-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_performancemonitoring_task_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemonitoring',
            name='due_date',
            field=models.DateTimeField(blank=True, help_text='Submission deadline.', null=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='teacher_remarks',
            field=models.TextField(blank=True, help_text='Specific feedback for this submission.'),
        ),
    ]
